### ISSUE TITLE
devkit not compatible with prettier@3

### ISSUE THREAD

**Issue by roldengarm** [nx-squeezer/squeezer#1332]
peer dependency for @nx-squeezer/devkit does not accept prettier@3:

![image](https://github.com/nx-squeezer/squeezer/assets/37638588/848bf508-269b-4c6d-87a7-216e474da76b)

**Comment by samuelfernandez** [comment]
@roldengarm new version compatible with prettier v3 was released https://github.com/nx-squeezer/squeezer/releases/tag/devkit%403.1.0
