### ISSUE TITLE
bug(workspace): renovate can't install dependencies because nrwl deps are fixed and nx-create-migrations.sh does no exist

### ISSUE THREAD

**Issue by WolfSoko** [nx-squeezer/squeezer#390]
Hi again, 

first thank you very much for your efforts in bringing all this tooling to nx. 

I finally found some time to apply your workspace tools to  a clean nx angular workspace project:
https://github.com/WolfSoko/nx-clean

Don't wonder about the missing renovate.yml and configs. The are in a different repo.  
You can find them here: 
https://github.com/WolfSoko/nx-renovate-self-hosted 

Currently there are some problems running the migration for nrwl with renovate: 

1. it looks like your nx deps are too strict. Therefore `npm ci --ignore-scripts` fails.
2. nx-create-migrations.sh is not found. I also didn't found it to be generated.  

The other errors are IMO just follow up errors.

Have a look here: 
https://github.com/WolfSoko/nx-clean/pull/38

```
File name: package.json
Command failed: npm ci --ignore-scripts
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nx-squeezer/workspace@1.2.0
npm ERR! Found: nx@15.6.3
npm ERR! node_modules/nx
npm ERR!   dev nx@"15.6.3" from the root project
npm ERR!   peer nx@">= 14 <= 16" from @nrwl/devkit@15.6.2
npm ERR!   node_modules/@nrwl/devkit
npm ERR!     @nrwl/devkit@"15.6.2" from @nx-squeezer/workspace@1.2.0
npm ERR!     node_modules/@nx-squeezer/workspace
npm ERR!       dev @nx-squeezer/workspace@"^1.2.0" from the root project
npm ERR!     @nrwl/devkit@"15.6.2" from ngx-deploy-npm@4.3.11
npm ERR!     node_modules/ngx-deploy-npm
npm ERR!       ngx-deploy-npm@"4.3.11" from @nx-squeezer/workspace@1.2.0
npm ERR!       node_modules/@nx-squeezer/workspace
npm ERR!         dev @nx-squeezer/workspace@"^1.2.0" from the root project
npm ERR!   10 more (@nrwl/cli, @nrwl/workspace, @nrwl/devkit, @nrwl/devkit, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer nx@"15.6.2" from @nx-squeezer/workspace@1.2.0
npm ERR! node_modules/@nx-squeezer/workspace
npm ERR!   dev @nx-squeezer/workspace@"^1.2.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: nx@15.6.2
npm ERR! node_modules/nx
npm ERR!   peer nx@"15.6.2" from @nx-squeezer/workspace@1.2.0
npm ERR!   node_modules/@nx-squeezer/workspace
npm ERR!     dev @nx-squeezer/workspace@"^1.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ubuntu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-01-29T12_54_16_041Z-debug-0.log

File name: package.json
Command failed: npm run prepare --if-present
sh: 1: husky: not found

File name: package.json
Command failed: bash nx-create-migrations.sh
bash: nx-create-migrations.sh: No such file or directory

File name: package.json
Command failed: npx --no-install nx migrate @nrwl/angular --from=@nrwl/angular@15.6.2 --to=@nrwl/angular@15.6.3
npm ERR! canceled
```

**Comment by samuelfernandez** [comment]
@WolfSoko Thanks for this issue report. I'll separate it:

* Should not happen, I'll fix dependencies to make it work with legacy peer deps. Interesting that this wasn't caught in the e2e pipeline, can be a timing issue because of a new version being released. The root cause seems to be https://github.com/bikecoders/ngx-deploy-npm/issues/470
* This is a follow-up issue. I expected that the [fix](https://github.com/nrwl/nx/pull/14578/files) on `nx` itself would come sooner and just had to make one change. Is this blocking you?

**Comment by WolfSoko** [comment]
> Should not happen, I'll fix dependencies to make it work with legacy peer deps.

FYI: My test repo [nx-clean](https://github.com/WolfSoko/nx-clean) is not using legacy-peer-deps.

**Comment by samuelfernandez** [comment]
Please keep that feedback coming! :)

**Comment by samuelfernandez** [comment]
@WolfSoko would you have a script to create `nx-clean`? I'd like to have a GitHub workflow to early test new versions and identify earlier dependency issues, something similar to https://github.com/bikecoders/ngx-deploy-npm/blob/main/.github/workflows/next-test.yml

**Comment by samuelfernandez** [comment]
@WolfSoko can you please try with [v1.2.1](https://github.com/nx-squeezer/squeezer/releases/tag/workspace%401.2.1)?

**Comment by WolfSoko** [comment]
> @WolfSoko would you have a script to create `nx-clean`? I'd like to have a GitHub workflow to early test new versions and identify earlier dependency issues, something similar to https://github.com/bikecoders/ngx-deploy-npm/blob/main/.github/workflows/next-test.yml


Yes, an automatic approach to have a clean nx repo with tooling would be awesome.
I will have a look at the ngx-deploy approach.
